### PR TITLE
enable highlighting of diff blocks in gutter background #78

### PR DESCRIPTION
**Pull request by claytonrcarter**
After I opened #78, I got inspired and worked up this PR.  I'm not very familiar with CS and Less, but it appears to work.  This includes a new config setting for highlighting the background color in the gutter, as well as tests.  I followed the code that adds the +/./- icons pretty closely, as you'll see.

Please review and let me know if I got anything wrong. Thank you!

### CODE REVIEW

**Comment by benogle** [comment]
Can you post a screenshot?

**Comment by claytonrcarter** [comment]
Oh, sure.  Do these cropped shots work?

Here is the background highlighting when the gutter icons aren't used:
screen shot 2015-12-02 at 3 55 53 pm

And here it is when gutter icons are being used:
screen shot 2015-12-02 at 3 56 25 pm

I think that the combo of gutter highlights and normal color markers (`|`) looks especially slick.  I didn't do anything about highlighting deleted lines because ... how?  (The normal red arrow marker still works.)  You can see that the regular gutter highlighting of the cursor line is still working while the background is highlighted.

**Comment by benogle** [comment]
Rather than add another option, can you add these styles in your `styles.less`?

cc @simurai

**Comment by claytonrcarter** [comment]
Ah, yes, well ... hmm.  I guess that does work, doesn't it?  I think it's legit to offer an option to make the gutter markers stand out more w/o using the icon markers, but fiddling with my local styles certainly solves my immediate needs.  Thanks for guiding me there.

**Comment by 50Wliu** [comment]
Just tried this out and it doesn't seem to work nicely with light themes:
darken

Using `lighten` instead of `darken`, I get this which looks much better:
lighten

Perhaps this is only because I just copied your styles into `styles.less` and removed the `git-diff-background` portion.

Using One Light and Fizzy.

**Comment by claytonrcarter** [comment]
I obviously didn't even think about light themes.  Flipping between different themes, it looks like Atom Light and One Light both would need different amounts of lightening.  For instance the following snippet looks nice in One Light but uneven and tacky in Atom Light.  And the bottom snippet looks nice in Atom Dark, but not so in One Dark.  In all of these cases, fiddling with *how much* the colors are lightened or darkened - even just a little bit - makes a huge difference.

@benogle do you see something like this going somewhere?  If so, I could look into creating some conditional mixins that would compare the `lightness()` of the `color` of `.gutter.line-number` vs the `background-color` of the `.gutter` to try to come up with highlight colors that might work across themes.  Otherwise, I will just leave this be.

In any event ... pardon my enthusiasm.

For light themes:
```
@import "syntax-variables";
atom-text-editor,
atom-text-editor::shadow {
  .gutter .line-number {
      &.git-line-modified {
        background-color: lighten( @syntax-color-modified, 35% );
      }

      &.git-line-added {
        background-color: lighten( @syntax-color-added, 40% );
      }

  }
}
```
For dark themes:
```
@import "syntax-variables";
atom-text-editor,
atom-text-editor::shadow {
  .gutter .line-number {
      &.git-line-modified {
        background-color: darken( @syntax-color-modified, 40% );
      }

      &.git-line-added {
        background-color: darken( @syntax-color-added, 50% );
      }

  }
}
```

**Comment by benogle** [comment]
IMO, we should keep the way it is currently, but I defer to @simurai.

**Comment by simurai** [comment]
The background colors could be semi transparent so that it works for dark and light backgrounds. Maybe something like:

```less
atom-text-editor::shadow .line-number {
  &.git-line-added {
    background-color: fade(@syntax-color-added, 10%);
  }
  &.git-line-modified {
    background-color: fade(@syntax-color-modified, 10%);
  }
}
```

or mixing them with the background:

```less
atom-text-editor::shadow .line-number {
  &.git-line-added {
    background-color: mix(@syntax-color-added, @syntax-gutter-background-color, 10%);
  }
  &.git-line-modified {
    background-color: mix(@syntax-color-modified, @syntax-gutter-background-color, 10%);
  }
}
```

Now if it should be added in `styles.less`, in themes, as a setting or the new default. Hmm.. I actually kinda like it. I'll keep it in my `styles.less` for a bit to see how it feels.

**Comment by johnmanko** [comment]
@claytonrcarter , do you have an estimate when all conflicts will be resolved?

**Comment by 50Wliu** [comment]
Something I noticed while (sorta kinda) testing this locally:
If the line I'm typing on has been modified, the cursor highlight isn't present, so I can't tell which line my cursor is on just by looking at the status bar.  Not sure if that's an issue with this PR or just the way I set it up in my `styles.less`.

**Comment by claytonrcarter** [comment]
Sorry, I wasn't aware that this developed conflicts.  Also, I haven't been using it because, as @benogle pointed out, I could just alter my `styles.less` to achieve the same effect, and I've been happy with how that works.  I'm inclined to withdraw this PR unless someone really, really wants me to update it.  (I'm very busy right now and it might a while before I can get to it.)

**Comment by simurai** [comment]
Closing this as `wontfix`. This seems like a good candidate to add in your `styles.less` and not as a new default.

@claytonrcarter Thanks for your PR though. 🙇

**Pull request closed without merging**
