### PR TITLE
Fix a bug where @editor.getPath() was assumed to always be non-null.

### PR DESCRIPTION
**Pull request by bolinfest**

### CODE REVIEW

**Comment by maxbrunsfeld** [comment]
I can't reproduce the exception that you're referring to. When were you experiencing an exception here?

**Comment by bolinfest** [comment]
Open Atom via Spotlight such that it opens with a tab named "untitled" that does not correspond to a file on disk.

**Comment by bolinfest** [comment]
What happens is that this calls through to `repositoryForPath(undefined)`:

```module.exports =
  repositoryForPath: (goalPath) ->
    for directory, i in atom.project.getDirectories()
      if goalPath is directory.getPath() or directory.contains(goalPath)
        return atom.project.getRepositories()[i]
    null
```

If the implementation of `directory.contains()` tolerates `undefined` as an argument, then you're OK, but it's not clear from the spec of `Directory` that it should tolerate such a thing. I think it's right for `contains()` to treat that as an error.

**Comment by maxbrunsfeld** [comment]
I see, so this is for when you have a custom `atom.directory-provider`. That seems reasonable. Could you add a test for this?

**Comment by bolinfest** [comment]
@maxbrunsfeld I'm working on it, but it's a little tricky because there's a bit of setup involved to create the project with a directory provider to reproduce the error. Not sure if I'll get to it today.

**Comment by bolinfest** [comment]
@maxbrunsfeld Thinking this over more, what do you want to see in a test? From my perspective, there is no bug with custom directory providers: they just happened to expose the bug.

The bug is that there was an inappropriate call to `Directory.contains(path)`, as a possibly null value was passed for `path`. In a static type system like Flow, you would never even write a test for a bug like this: you would just tighten the contract of `contains()` to take a `string` rather than a `?string` (which is what the 1.0 docs say it should take) and fix any typecheck errors that result.

I suppose I could write a test that verifies that if `@editor.getPath()` returns `null`, then `repositoryForPath()` is not called in `subscribeToRepository()`, but that seems like a potentially brittle test. What sort of breakage would that defend against in the future?

**Comment by bolinfest** [comment]
@maxbrunsfeld I'm not sure what Atom's policy is on writing code to verify arguments. For example, should `Directory.contains(path)` throw an exception if `path` is `null`?

Or if it should accept `null`, then I think the public API should be changed to specify that, in which case I will update my custom `Directory` to implement the API and abandon this PR. (Though I think an API that silently swallows `null` is likely to mask other programmer errors, so I wouldn't recommend this approach.)

In our packages, we rely on Flow to do the checking statically so we don't write code that is used for runtime argument checks.

**Comment by bolinfest** [comment]
It seems pretty common to use `editor.getPath()` with `Directory::contains()`, so I'm just going to close this and change our `contains()` to accept `null`.

**Pull request closed without merging**
